name: Promote firmware on Cloudflare R2

on:
  workflow_call:
    inputs:
      version:
        description: Version of the firmware to promote
        required: true
        type: string
      directory:
        description: Directory to promote the firmware to
        required: true
        type: string
      channel:
        description: Channel to upload to. "beta" or "production"
        required: false
        type: string
        default: "beta"
      manifest-filename:
        description: Filename of the manifest to write.
        required: false
        type: string
        default: manifest-beta.json

jobs:
  promote:
    name: Promote ${{ inputs.version }} to ${{ inputs.channel }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.channel }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          path: files

      - name: Build ${{ inputs.manifest-filename }}
        run: |
          mkdir -p output
          version="${{ inputs.version }}"
          manifest_filename="${{ inputs.manifest-filename }}"
          echo "Version: $version"
          echo "Manifest filename: $manifest_filename"
          echo "Files directory contents:"
          ls -la files/
          
          # Find the first device directory and use its manifest
          device_path=$(find files -maxdepth 1 -type d ! -name files | head -1)
          if [ -n "$device_path" ]; then
            device=$(basename "$device_path")
            echo "Using device: $device"
            
            manifest_path="$device_path/$version/manifest.json"
            echo "Looking for manifest at: $manifest_path"
            
            if [ -f "$manifest_path" ]; then
              echo "Found manifest file"
              
              # Copy the version directory (keeps original manifest.json)
              mkdir -p "output/$version"
              cp -r "$device_path/$version/"* "output/$version/"
              echo "Copied version $version directory"
              
              # Also create manifest-beta.json in root with updated paths
              jq --arg version "$version" \
                '.builds[].ota.path |= $version + "/" + . | (.builds[].parts // [])[].path |= $version + "/" + .' \
                "$manifest_path" > "output/$manifest_filename"
              echo "Created $manifest_filename in output root"
            else
              echo "Error: Manifest not found at $manifest_path"
              echo "Available files in $device_path:"
              ls -la "$device_path/" || echo "Device path not accessible"
              exit 1
            fi
          else
            echo "Error: No device directory found in files/"
            ls -la files/
            exit 1
          fi
          
          echo "Final output contents:"
          find output -type f

      - name: Upload ${{ inputs.manifest-filename }} to R2
        uses: ryand56/r2-upload-action@v1.4
        with:
          r2-account-id: ${{ secrets.CF_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.CF_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.CF_BUCKET_NAME }}
          source-dir: output
          destination-dir: ${{ inputs.directory }}/
