name: Upload firmware to GitHub Release

on:
  workflow_call:
    inputs:
      version:
        description: Version of the release
        required: true
        type: string
      prerelease:
        description: Whether this is a prerelease
        required: false
        default: false
        type: boolean
    secrets:
      PAT_TOKEN:
        description: 'Optional Personal Access Token for creating releases'
        required: false

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          path: files

      - name: Copy files to output
        run: |-
          shopt -s nullglob
          mkdir output
          version="${{ inputs.version }}"
          
          echo "=== DEBUG INFO ==="
          echo "Input version: $version"
          echo "Files directory contents:"
          ls -la files/
          echo "==================="
          
          pushd files
          for device in *; do
            echo "=== Processing folder: '$device' ==="
            echo "Current working directory: $(pwd)"
            pushd $device
            echo "Contents of device folder '$device':"
            ls -la
            
            if [ -d "$version" ]; then
              echo "Found version directory '$version', entering..."
              pushd $version
              echo "Contents of version directory '$version':"
              ls -la
              echo "Copying manifest.json to: $device.manifest.json"
              cp manifest.json ../../../output/$device.manifest.json
              for bin in *.{bin,elf}; do
                echo "Processing binary: $bin"
                md5sum $bin | head -c 32 > ../../../output/$bin.md5
                cp $bin ../../../output/
              done
              popd
            else
              echo "No version directory '$version' found, checking for direct manifest..."
              if [ -f "manifest.json" ]; then
                echo "Found direct manifest.json, copying to: $device.manifest.json"
                cp manifest.json ../../output/$device.manifest.json
                for bin in *.{bin,elf}; do
                  if [ -f "$bin" ]; then
                    echo "Processing binary: $bin"
                    md5sum $bin | head -c 32 > ../../output/$bin.md5
                    cp $bin ../../output/
                  fi
                done
              else
                echo "No manifest.json found in device folder"
              fi
            fi
            popd
            echo "=== Finished processing '$device' ==="
          done
          popd
          
          echo "=== FINAL OUTPUT ==="
          echo "Contents of output directory:"
          ls -la output/
          echo "===================="

      - name: Upload files to release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: output/*
          tag_name: ${{ inputs.version }}
          draft: false
          prerelease: ${{ inputs.prerelease }}
          token: ${{ secrets.PAT_TOKEN || github.token }}