name: Upload firmware to GitHub Release

on:
  workflow_call:
    inputs:
      version:
        description: Version of the release
        required: true
        type: string
      prerelease:
        description: Whether this is a prerelease
        required: false
        default: false
        type: boolean

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          path: files

      - name: Copy files to output
        run: |-
          shopt -s nullglob
          mkdir output
          version="${{ inputs.version }}"
          pushd files
          for device in *; do
            pushd $device
            if [ -d "$version" ]; then
              pushd $version
              cp manifest.json ../../../output/$device.manifest.json
              for bin in *.{bin,elf}; do
                md5sum $bin | head -c 32 > ../../../output/$bin.md5
                cp $bin ../../../output/
              done
              popd
            else
              echo "Warning: Version directory $version not found in device $device"
              echo "Available directories:"
              ls -la
              # Try to find files in current directory as fallback
              if [ -f "manifest.json" ]; then
                echo "Found manifest.json in device root, using as fallback"
                cp manifest.json ../../output/$device.manifest.json
                for bin in *.{bin,elf}; do
                  if [ -f "$bin" ]; then
                    md5sum $bin | head -c 32 > ../../output/$bin.md5
                    cp $bin ../../output/
                  fi
                done
              fi
            fi
            popd
          done
          popd

      - name: Upload files to release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: output/*
          tag_name: ${{ inputs.version }}
          draft: false
          prerelease: ${{ inputs.prerelease }}
