name: Upload firmware to Cloudflare R2

on:
  workflow_call:
    inputs:
      directory:
        description: Directory to upload to
        required: true
        type: string

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          path: files

      - name: Upload files to R2
        uses: ryand56/r2-upload-action@v1.4
        with:
          r2-account-id: ${{ secrets.CF_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.CF_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.CF_BUCKET_NAME }}
          source-dir: files
          destination-dir: ${{ inputs.directory }}/
